# Generated by Django 5.2 on 2025-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_rename_actors_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('AFEGANISTÃO', 'Afghanistan'), ('ALEMANHA', 'Germany'), ('ARGENTINA', 'Argentina'), ('AUSTRÁLIA', 'Australia'), ('ÁUSTRIA', 'Austria')], max_length=100, null=True),
        ),
    ]
