# Generated by Django 5.2 on 2025-04-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
